server:
  servlet:
    encoding:
      charset: utf-8
      force: true
spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      schema-locations:
      - classpath:db/schema.sql
      data-locations:
      - classpath:db/data.sql
  h2:
    console:
      enabled: true
  output:
    ansi:
      enabled: always
  mail:
    default-encoding: utf-8
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          sockFactory.class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
  - classpath:/mapper/**.xml

logging:
  level:
    '[com.snowball.boardadmin]': DEBUG
